### ISSUE TITLE
questions about waveman

### ISSUE THREAD

**Issue by mikeyEcology** [chenxing3/Waveman#1]
Hi,
I just started playing with Waveman and I have a few questions:
1) If I don't separate the images into categories ('strong', 'weak') can I still train a model? It seems like I can, and this would be what you refer to in the manuscript as the dataset-without-weak, which had lower accuracy. I'm new to accoustic machine learning methods. Is this type of scoring something that is commonly done?
2) In the paper you mentioned a few architectures (ResNet, CnnFull), are these available to use in this package? Or is BatNet the only one available. 
3) The documentation for this package is great and I appreciate it!

Thank you

**Comment by chenxing3** [comment]
Hi,


Thank you would like to use Waveman.


1. For my datasets, the accuracy rate is not as high as 'weak' categories, which I described in the paper. Maybe the model is sensitive to the weak signals.  But you can train your model without 'weak' categories, despite low performance of my datasets. There are no rules to limited you to define categories (But you should balance the image numbers among categories. I mean the images numbers are not too variable among categories (suggest the number less than 10 times); otherwise the CNN-based model just ignore the categories only with little images).


To evaluate the results from Waveman, I have a set of well-annotated images, so I can calculate the overall accuracy, false positives etc. You can choose some typical audios or images to annotate and to evaluate models Waveman generated.


By the way, I faced the problem of a lot of the heavy work on the manual classification. So I used Kaleidoscope to extract bat signal regions from audio files. Then convert selected files into images. Images from the interval of pulses are enough for preparing weak/no-call categories. And currently, we are trying to develop a method based on RNN to make the classification easier. It can extract all the bats pulses (regardless species) just in one run, and I hope it can preprocess large volume of data fast.


2. For the other two architectures in the paper (ResNet, CNN-Full), I didn't put them into the Waveman since the parameter settings are different from BatNet and Vgg. I mean I cannot just change the model function in Waveman (https://github.com/chenxing3/Waveman/blob/master/utils/MODEL.py). But I have the scripts for just testing (I didn't annotate the script well). If you want run it, I can send the scripts to you. 


Best wishes for you in this uncertain time,
Xing
10/04/2020








------------------ Original ------------------

**Comment by mikeyEcology** [comment]
Thank you for your responses @chenxing3!
I'll be getting some data soon and I look forward to trying this software on my data. I'll let you know if I want to try the other architectures based on how I do with BatNet and Vgg. 
Best wishes,
Mikey
